---
- hosts: all
  vars:
    - user: "vagrant"
  become: yes

  tasks:
    - name: Add podman apt key
      apt_key:
        url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key"
        state: present

    - name: Add podman apt repository
      apt_repository:
        repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /"
        state: present
        filename: "devel:kubic:libcontainers:stable"
        update_cache: yes

    - name: Upgrading OS
      ansible.builtin.apt:
        update_cache: yes

    - name: Installing container technologies (docker, podman)
      ansible.builtin.apt:
        name:
          - podman
          - docker.io
        state: present

    - name: Start docker and podman services
      service:
        name: '{{ item }}'
        state: started
      loop:
        - docker
        - podman


    - name: Adding '{{ user }}' user to docker group
      user:
        name: '{{ user }}'
        groups: docker
        append: yes

    - name: setup podman in a rootless enviroment
      ansible.builtin.copy:
        src: 'podman/{{ item }}'
        dest: /etc
      loop:
        - subuid
        - subgid

    - name: Installing java development tools (openjdk11, gradle, git)
      ansible.builtin.apt:
        name:
          - gradle
          - openjdk-11-jdk
          - git
        state: present
